/* Generated By:JavaCC: Do not edit this line. langXConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface langXConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BREAK = 12;
  /** RegularExpression Id. */
  int CLASS = 13;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int EXTENDS = 16;
  /** RegularExpression Id. */
  int FOR = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int INT = 19;
  /** RegularExpression Id. */
  int NEW = 20;
  /** RegularExpression Id. */
  int PRINT = 21;
  /** RegularExpression Id. */
  int READ = 22;
  /** RegularExpression Id. */
  int RETURN = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int SUPER = 25;
  /** RegularExpression Id. */
  int WHILE = 26;
  /** RegularExpression Id. */
  int DO = 27;
  /** RegularExpression Id. */
  int SWITCH = 28;
  /** RegularExpression Id. */
  int CASE = 29;
  /** RegularExpression Id. */
  int DEFAULTT = 30;
  /** RegularExpression Id. */
  int CHAR = 31;
  /** RegularExpression Id. */
  int BOOLEAN = 32;
  /** RegularExpression Id. */
  int DOUBLE = 33;
  /** RegularExpression Id. */
  int BYTE = 34;
  /** RegularExpression Id. */
  int SHORT = 35;
  /** RegularExpression Id. */
  int LONG = 36;
  /** RegularExpression Id. */
  int FLOAT = 37;
  /** RegularExpression Id. */
  int FINAL = 38;
  /** RegularExpression Id. */
  int PUBLIC = 39;
  /** RegularExpression Id. */
  int PRIVATE = 40;
  /** RegularExpression Id. */
  int PROTECTED = 41;
  /** RegularExpression Id. */
  int int_constant = 42;
  /** RegularExpression Id. */
  int string_constant = 43;
  /** RegularExpression Id. */
  int null_constant = 44;
  /** RegularExpression Id. */
  int boolean_constant = 45;
  /** RegularExpression Id. */
  int char_constant = 46;
  /** RegularExpression Id. */
  int double_constant = 47;
  /** RegularExpression Id. */
  int byte_constant = 48;
  /** RegularExpression Id. */
  int short_constant = 49;
  /** RegularExpression Id. */
  int long_constant = 50;
  /** RegularExpression Id. */
  int float_constant = 51;
  /** RegularExpression Id. */
  int IDENT = 52;
  /** RegularExpression Id. */
  int LETTER = 53;
  /** RegularExpression Id. */
  int DIGIT = 54;
  /** RegularExpression Id. */
  int LPAREN = 55;
  /** RegularExpression Id. */
  int RPAREN = 56;
  /** RegularExpression Id. */
  int LBRACE = 57;
  /** RegularExpression Id. */
  int RBRACE = 58;
  /** RegularExpression Id. */
  int LBRACKET = 59;
  /** RegularExpression Id. */
  int RBRACKET = 60;
  /** RegularExpression Id. */
  int SEMICOLON = 61;
  /** RegularExpression Id. */
  int COMMA = 62;
  /** RegularExpression Id. */
  int DOT = 63;
  /** RegularExpression Id. */
  int DOISP = 64;
  /** RegularExpression Id. */
  int ASSIGN = 65;
  /** RegularExpression Id. */
  int GT = 66;
  /** RegularExpression Id. */
  int LT = 67;
  /** RegularExpression Id. */
  int EQ = 68;
  /** RegularExpression Id. */
  int LE = 69;
  /** RegularExpression Id. */
  int GE = 70;
  /** RegularExpression Id. */
  int NEQ = 71;
  /** RegularExpression Id. */
  int PLUS = 72;
  /** RegularExpression Id. */
  int MINUS = 73;
  /** RegularExpression Id. */
  int STAR = 74;
  /** RegularExpression Id. */
  int SLASH = 75;
  /** RegularExpression Id. */
  int REM = 76;
  /** RegularExpression Id. */
  int AND = 77;
  /** RegularExpression Id. */
  int OR = 78;
  /** RegularExpression Id. */
  int XOR = 79;
  /** RegularExpression Id. */
  int NOT = 80;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 81;
  /** RegularExpression Id. */
  int INVALID_CONST = 82;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "<token of kind 11>",
    "\"break\"",
    "\"class\"",
    "\"constructor\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"if\"",
    "\"int\"",
    "\"new\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"string\"",
    "\"super\"",
    "\"while\"",
    "\"do\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"char\"",
    "\"boolean\"",
    "\"double\"",
    "\"byte\"",
    "\"short\"",
    "\"long\"",
    "\"float\"",
    "\"final\"",
    "\"public\"",
    "\"private\"",
    "\"protected\"",
    "<int_constant>",
    "<string_constant>",
    "\"null\"",
    "<boolean_constant>",
    "<char_constant>",
    "<double_constant>",
    "<byte_constant>",
    "<short_constant>",
    "<long_constant>",
    "<float_constant>",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&&\"",
    "\"||\"",
    "\"^\"",
    "\"!\"",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
  };

}
